name: GuBu-Service CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['GuBu-Service CI']
    types: [completed]
    branches: [main]
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Ubuntu
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PEMKEY }}
          port: ${{ secrets.SERVER_SSH }}
          script: |
            # Load nvm and node environment
            export NVM_DIR="/home/ubuntu/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            cd /home/ubuntu/8jo/cicd_test

            git switch main

            git pull

            echo "${{ secrets.SERVER_ENV1 }}" > .env
            echo "${{ secrets.SERVER_ENV2 }}" >> .env
            echo "${{ secrets.SERVER_ENV3 }}" >> .env
            echo "${{ secrets.SERVER_ENV4 }}" >> .env
            echo "${{ secrets.SERVER_ENV5 }}" >> .env
            echo "${{ secrets.SERVER_ENV6 }}" >> .env
            echo "${{ secrets.SERVER_ENV7 }}" >> .env
            echo "${{ secrets.SERVER_ENV8 }}" >> .env
            echo "${{ secrets.SERVER_ENV9 }}" >> .env
            echo "${{ secrets.SERVER_ENV10 }}" >> .env

            npm ci

            npm run build

            pm2 delete gubu-service || true

            pm2 start dist/main.js --name gubu-service

            pm2 save