name: GuBu-Service CI

on:
  workflow_dispatch:
  push:
    branches: [dev, main]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [dev, main]

jobs:
  ci-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Build
        run: npm run build

      - name: Archive build
        run: tar -czf gubu-service.tar.gz dist/

      - name: Copy build to deployment server
        run: |
          scp -i ${{ secrets.SERVER_PEMKEY }} -P ${{ secrets.SERVER_SSH }} gubu-service.tar.gz ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/ubuntu/8jo/cicd_test/